import type { Metadata } from "next";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { Nanum_Gothic } from 'next/font/google';
import { ThemeProvider } from "@mui/material";
import theme from "./theme";

const nanumGothic = Nanum_Gothic({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nanum-gothic'
})

export const metadata: Metadata = {
  title: "Ivan Uria's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nanumGothic.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
