import type { Metadata } from "next";

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { Nanum_Gothic, Righteous } from 'next/font/google';
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "../theme";

const nanumGothic = Nanum_Gothic({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-primary'
})

const righteous = Righteous({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-secondary'
})

export const metadata: Metadata = {
  title: "Ivan Uria's Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang="en">
      <CssBaseline />
      <body className={[nanumGothic.variable, righteous.variable].join(' ')}>
        <NextIntlClientProvider messages={messages}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
