// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export { type Id, type default as Locales, type LocalesInitializer, type LocalesMutator, id, locales, localesInitializer, localesMutator } from './Locales';
